### ISSUE TITLE
Documentation request:  clarify why use this action

### ISSUE THREAD

**Issue by larryclaman** [Azure/docker-login#28]
I'd like to see something in the README that explains why someone should use this action versus just calling 'docker login' directly.

I'm not trying to be critical or snarky, rather, it's just that when I review the README for this action, it's not apparent to me what functionality or value the action provides versus just running a one liner `run: docker login  <loginserver> -u <username> -p <password>`.   Would be great if some additional info or context was added.

**Comment by thesattiraju** [comment]
When you use the above command, the secrets are exposed through the commandline for the process. So if your runner is compromised, your docker credentials are compromised.

The major use of this action is to avoid the above security issue. 

We avoid it by creating the file which the same command eventually generates without logging your secrets anywhere; we create that file in a temp directory instead of the home of the runner. This triggers a clean up as soon as the workflow context ends. 

The alternative for this action is using the command like this `cat ~/my_password.txt | docker login --username foo --password-stdin` also additionally cleaning up the `my_password.txt` file after your workflow is done.
