### ISSUE TITLE
Node 12 is deprecated, move to node 16

### ISSUE THREAD

**Issue by StoyanStAtanasov** [Azure/docker-login#43]
Got this warning message from github actions: 
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16:  azure/docker-login, ...

**Comment by SeanKilleen** [comment]
Wouldn't normally do this, but since we're only 5 days away from the breakage that could affect many repos,, going to ping a few of the repository contributors on this.

* Announcement that Node 12 will be removed on 11/14: https://github.com/actions/runner-images/issues/6482
* PR to fix this: #44

CCing the following accounts in case they can find a path to get someone to merge the PR & cut a new release:

@thesattiraju @microsoftopensource @sundargs2000 @ajinkya599

**Comment by 5minpause** [comment]
@SeanKilleen new pr was opened https://github.com/Azure/docker-login/pull/45

**Comment by BALAGA-GAYATRI** [comment]
Merged the necessary PRs.

**Comment by mechelewskim** [comment]
@BALAGA-GAYATRI, could you please additionally move the `v1` tag?
I don't want to use the `master` version of the workflow as some breaking changes can be pushed directly into master.
